2021-08-15 16:20:26,094 INFO    MainThread:13134 [wandb_setup.py:_flush():69] setting env: {}
2021-08-15 16:20:26,094 INFO    MainThread:13134 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-15 16:20:26,094 INFO    MainThread:13134 [wandb_init.py:_log_setup():337] Logging user logs to /cs/labs/josko/nirm/embryo_project_version1/embyo_projects_codes/lord-pytorch-unet/wandb/run-20210815_162026-bbr8zlzv/logs/debug.log
2021-08-15 16:20:26,094 INFO    MainThread:13134 [wandb_init.py:_log_setup():338] Logging internal logs to /cs/labs/josko/nirm/embryo_project_version1/embyo_projects_codes/lord-pytorch-unet/wandb/run-20210815_162026-bbr8zlzv/logs/debug-internal.log
2021-08-15 16:20:26,094 INFO    MainThread:13134 [wandb_init.py:init():370] calling init triggers
2021-08-15 16:20:26,094 INFO    MainThread:13134 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-08-15 16:20:26,094 INFO    MainThread:13134 [wandb_init.py:init():419] starting backend
2021-08-15 16:20:26,094 INFO    MainThread:13134 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-15 16:20:26,100 INFO    MainThread:13134 [backend.py:ensure_launched():135] starting backend process...
2021-08-15 16:20:26,106 INFO    MainThread:13134 [backend.py:ensure_launched():140] started backend process with pid: 13189
2021-08-15 16:20:26,107 INFO    MainThread:13134 [wandb_init.py:init():424] backend started and connected
2021-08-15 16:20:26,108 INFO    MainThread:13134 [wandb_init.py:init():472] updated telemetry
2021-08-15 16:20:26,108 INFO    MainThread:13134 [wandb_init.py:init():491] communicating current version
2021-08-15 16:20:26,821 INFO    MainThread:13134 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.12.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-15 16:20:26,821 INFO    MainThread:13134 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-08-15 16:20:27,185 INFO    MainThread:13134 [wandb_init.py:init():529] starting run threads in backend
2021-08-15 16:20:27,246 INFO    MainThread:13134 [wandb_run.py:_console_start():1623] atexit reg
2021-08-15 16:20:27,248 INFO    MainThread:13134 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.REDIRECT
2021-08-15 16:20:27,248 INFO    MainThread:13134 [wandb_run.py:_redirect():1502] Redirecting console.
2021-08-15 16:20:27,249 INFO    MainThread:13134 [wandb_run.py:_redirect():1558] Redirects installed.
2021-08-15 16:20:27,249 INFO    MainThread:13134 [wandb_init.py:init():554] run started, returning control to user process
2021-08-15 16:20:34,221 INFO    MainThread:13134 [wandb_run.py:_atexit_cleanup():1593] got exitcode: 1
2021-08-15 16:20:34,221 INFO    MainThread:13134 [wandb_run.py:_restore():1565] restore
2021-08-15 16:20:36,322 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1042
  total_bytes: 1042
}

2021-08-15 16:20:36,697 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1042
  total_bytes: 1042
}

2021-08-15 16:20:37,201 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 1042
  total_bytes: 1332
}

2021-08-15 16:20:37,301 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1042
  total_bytes: 7229
}

2021-08-15 16:20:37,402 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1042
  total_bytes: 7229
}

2021-08-15 16:20:37,503 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1042
  total_bytes: 7229
}

2021-08-15 16:20:37,604 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1042
  total_bytes: 7229
}

2021-08-15 16:20:37,705 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:37,806 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:37,907 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:38,008 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:38,109 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:38,210 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:38,420 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:38,521 INFO    MainThread:13134 [wandb_run.py:_wait_for_finish():1715] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7229
  total_bytes: 7229
}

2021-08-15 16:20:39,564 INFO    MainThread:13134 [wandb_run.py:_show_files():1937] logging synced files
